### ISSUE TITLE
Can't Pickle

### ISSUE THREAD

**Issue by Frogdo** [Mechazawa/whatbetter-crawler#1]
I've been bending over my computer trying to get this to work for the past three hours.  I've reinstalled Python several times and downloaded all dependencies.  My config works because What.CD correctly authenticates, but when the script attempts to transcode I get an error message like this:
>Formats needed: 320, V2
Adding format 320... Error adding format 320: Can't pickle <function pool_initializer at 0x02CFB6F0>: it's not found as transcode.pool_initializer
Adding format V2... Error adding format V2: Can't pickle <function pool_initializer at 0x02FE1570>: it's not found as transcode.pool_initializer
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError

My Python version is 2.7.11.
Thanks for any help!

**Comment by anhydro** [comment]
This really isn't constructive, but WhatBetter wasn't designed to run under Windows in any sense of the project.

If you really want to get it running, all else fails, map a Virtual Machine to your data folder, then just run it from within the VM. I've done it, and all you end up having to do is fixing your permissions on the Windows end.

**Comment by Mechazawa** [comment]
I'll change it to something else then pickle. Like @anhydro said, the application was made for *nix systems.

**Comment by Mechazawa** [comment]
@Frogdo Can you try out [this branch](https://github.com/Mechazawa/whatbetter-crawler/tree/pickle_remove)?
