### ISSUE TITLE
Error when i try to run whatbetter

### ISSUE THREAD

**Issue by BinaryCode101101** [Mechazawa/whatbetter-crawler#5]
Last login: Tue Jun 28 20:33:53 2016 from 70.15.7.141
[briareus ~] ~/.local/bin/whatbetter
Logging in to What.CD...
Searching for transcode candidates...

Traceback (most recent call last):
  File "/media/sdaj1/binaryc0de/.local/bin/whatbetter", line 4, in <module>
    __import__('pkg_resources').run_script('whatbetter==1.3', 'whatbetter')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_scr                                                                                                                                                             ipt
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_sc                                                                                                                                                             ript
    exec(script_code, namespace, namespace)
  File "/media/sdaj1/binaryc0de/.local/lib/python2.7/site-packages/whatbetter-1.                                                                                                                                                             3-py2.7.egg/EGG-INFO/scripts/whatbetter", line 228, in <module>

  File "/media/sdaj1/binaryc0de/.local/lib/python2.7/site-packages/whatbetter-1.                                                                                                                                                             3-py2.7.egg/EGG-INFO/scripts/whatbetter", line 140, in main

UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-20: ord                                                                                                                                                             inal not in range(128)
[briareus ~] ~/.local/bin/whatbetter
Logging in to What.CD...
Searching for transcode candidates...

Traceback (most recent call last):
  File "/media/sdaj1/binaryc0de/.local/bin/whatbetter", line 4, in <module>
    __import__('pkg_resources').run_script('whatbetter==1.3', 'whatbetter')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/media/sdaj1/binaryc0de/.local/lib/python2.7/site-packages/whatbetter-1.3-py2.7.egg/EGG-INFO/scripts/whatbetter", line 228, in <module>

  File "/media/sdaj1/binaryc0de/.local/lib/python2.7/site-packages/whatbetter-1.3-py2.7.egg/EGG-INFO/scripts/whatbetter", line 140, in main

UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-20: ordinal not in range(128)
[briareus ~]

Complete noob at linux/python so not sure what went wrong here

**Comment by anhydro** [comment]
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-20: ordinal not in range(128)`

Looks like your snatch list has unicode characters in it.

`LC_CTYPE=en_US.UTF-8 python ~/.local/bin/whatbetter`


Kind of hacky, but it'll tell you if unicode support is present (if the script runs). Try contacting (I'm assuming, because of briareus) Feral about having the unicode locales rebuilt. Should work after then.
